#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
#=================================================

name: Build System Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]
#  schedule:
#    - cron: 0 8 * *

env:
  SSH_ACTIONS: true

jobs:

  build:
    runs-on: ubuntu-16.04

    env:
      DEVICE: onyx
      ANDROID_ROOT: /home/runner/work/b2g/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc autoconf-2.13 \
        bison build-essential curl flex g++-multilib m4 libxml2-utils \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool flex \
        libncurses5-dev libsdl1.2-dev libssl-dev repo libwxgtk3.0-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool ccache bison \
        squashfs-tools xsltproc yasm zip zlib1g-dev git
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
    - name: Downloading source code
      run: |
        source b2g.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/b2g2onyxL/B2G -b b2g/cm-12.1 --depth=1
        cd ./B2G
        ./config onyx

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Build HAL
      run: |
        source b2g.env
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot image
        path: /home/runner/work/b2g/B2G/out/target/product/onyx/boot.img

    - name : Upload system image
      uses: actions/upload-artifact@master
      with:
        name: System image
        path: /home/runner/work/b2g/B2G/out/target/product/onyx/system.img 

    - name : Upload update.zip
      uses: actions/upload-artifact@master
      with:
        name: update.zip
        path: /home/runner/work/b2g/B2G/out/target/product/onyx/fota/fullimg/update.zip
